### ISSUE TITLE
excel 

### ISSUE THREAD

**Issue by allenaven** [carlopacioni/HexSimR#4]
Hi, thanks for making an excellent complement to the also excellent HexSim tool. I'd like to ask about the dependencies related to MS Excel/Java in the package. Unfortunately those dependencies make HexSimR unusable for me.
- Is there a workaround that I haven't noticed? 
- Is it possible to circumvent those dependencies by returning R dataframe or list objects from the HexSimR functions, and then letting the user handle further postprocessing ad lib?

thanks!

**Comment by carlopacioni** [comment]
Hi Allen,
thanks for your kind words about HexSimR. I'm sorry to hear you are having trouble with HexSimR dependencies. What kind of problems are you having? In theory the XLConnect package should be compatible with all OS. Is there a particular function that you need to use?

I’m afraid that circumvent the current set up will require a fair bit of work as the outputs of some functions are the inputs of others and the changing of the output format will cause a cascade of changes and require running several tests. Please, do provide more details about what your problem is. I’m happy to see whether I can help to solve your installation problems or find an alternative solution if possible.

Carlo

**Comment by carlopacioni** [comment]
Hi Allen,
I didn't hear from you, so I'm going to close this. As a side note I have realised that the current official release of devtools (1.12.0) has an issue with R 3.3.1 on windows and results in the dependencies of the package not being installed. This problem is resolved in the dev version. To install the development version of devtools from github you can follow the instruction in devtools manual for the function build_github_devtools. I'll also put a note on the readme file.

carlo

**Comment by allenaven** [comment]
Yes sir! First, my apologies for never getting back on this. I'm finishing up a dissertation and everything else in my life right now is being neglected. I do appreciate your return communication, please forgive my poor manners.

Interesting to hear the issue with devtools. That may be what was causing me grief. I ended up resolving my immediate need by writing a couple of ad hoc functions to do what I needed done with some Hexsim simulation result datasets. Thinking longer term, though, my personal workflow doesn't include Excel and never will, and I (selfishly) can't help but wish that Hexsim might generate results straight into an `.rda` file without need for an intermediate.

Again, thank you for making excellent open-source software.

Allen

**Comment by carlopacioni** [comment]
Hi Allen,
while working on something else, it just occurred to me that XLConnect doesn't actually need to have excel installed to work, and that you can import the results of HexSimR functions directly in R using 
readWorksheetFromFile(file, ...). hence, you can use HexSimR without ever using excel.

cheers

**Comment by allenaven** [comment]
Hi Carlo, that sounds like a great workaround! Thanks for letting me know! Much appreciated.

--Allen

**Comment by carlopacioni** [comment]
;-)
